name: desktop_keep_screen_on
description: A Flutter plugin to keep screen on for desktop.
version: 0.0.2
homepage: https://github.com/MixinNetwork/flutter-plugins

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dbus: ^0.7.8
  synchronized: ^3.0.0
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DesktopKeepScreenOnPlugin
      windows:
        pluginClass: DesktopKeepScreenOnPluginCApi
      linux:
        dartPluginClass: DesktopKeepScreenOnLinux
