name: win_toast_example
description: Demonstrates how to use the win_toast plugin.

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  win_toast:
    path: ../
  cupertino_icons: ^1.0.2
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  msix: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.png

msix_config:
  display_name: WinToastExample
  identity_name: one.mixin.WinToastExample
  toast_activator:
    clsid: "9914995E-3B9A-4E86-A7AA-B2759C147211"
    arguments: "-ToastActivated"
    display_name: "WinToastExample"
  msix_version: 1.0.4.0