include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_classes_with_only_static_members: ignore
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    avoid_function_literals_in_foreach_calls: ignore
    control_flow_in_finally: true

linter:
  rules:
    prefer_const_constructors_in_immutables: true
    prefer_relative_imports: true
    prefer_final_locals: true
    avoid_void_async: true
    always_put_required_named_parameters_first: true
    unnecessary_await_in_return: true
    prefer_expression_function_bodies: true
    avoid_field_initializers_in_const_classes: true
    file_names: true
    unnecessary_parenthesis: true
    prefer_void_to_null: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_returning_null_for_void: true
    prefer_function_declarations_over_variables: true
    empty_statements: true
    prefer_is_not_operator: true
    cast_nullable_to_non_nullable: true
    type_annotate_public_apis: true
    prefer_const_literals_to_create_immutables: true
    use_named_constants: true
    use_string_buffers: true
    unnecessary_raw_strings: true
    unnecessary_null_checks: true
    parameter_assignments: true
    prefer_const_declarations: true
    sort_unnamed_constructors_first: true
    use_setters_to_change_properties: true
    curly_braces_in_flow_control_structures: true
