// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/breakpad_client.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class BreakpadClientBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BreakpadClientBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BreakpadClientBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void init_breakpad_exception_handler(
    ffi.Pointer<ffi.Char> dir,
  ) {
    return _init_breakpad_exception_handler(
      dir,
    );
  }

  late final _init_breakpad_exception_handlerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'init_breakpad_exception_handler');
  late final _init_breakpad_exception_handler =
      _init_breakpad_exception_handlerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}
