name: ogg_opus_player
resolution: workspace
description: An ogg opus file player and recorder for flutter.
version: 0.8.1
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/ogg_opus_player

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  system_clock: ^2.0.0

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      ios:
        pluginClass: SwiftOggOpusPlayerPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: SwiftOggOpusPlayerPlugin
        sharedDarwinSource: true
      android:
        package: one.mixin.oggOpusPlayer
        pluginClass: OggOpusPlayerPlugin
