name: ogg_opus_player
description: An ogg opus file player and recorder for flutter.
version: 0.7.0
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/ogg_opus_player

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  system_clock: ^2.0.0

dev_dependencies:
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      ios:
        pluginClass: OggOpusPlayerPlugin
      macos:
        pluginClass: OggOpusPlayerPlugin
      android:
        package: one.mixin.oggOpusPlayer
        pluginClass: OggOpusPlayerPlugin
