name: common_crypto
description: apple CommonCrypto ffi bindings for Dart.
version: 0.0.1
homepage: https://github.com/MixinNetwork/flutter-plugins

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

platforms:
  ios:
  macos:

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0

dev_dependencies:
  ffigen: ^8.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0