name: bring_window_to_front
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/bring_window_to_front

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      linux:
        pluginClass: BringWindowToFrontPlugin